# See https://reuse.software/spec-3.3/#reusetoml for specification
version = 1


[[annotations]]
path = [
    "Makefile",
    "*.mk",
    "*.act.json",
    "gen/*act.json",
    "gen/src/**",
    "gen/yang/cfs/*.yang",
    "gen/yang/inter/*.yang",
    "gen/yang/rfs/*.yang",
    "src/**",
    "test/**",
    ".devcontainer/**",
]
SPDX-FileCopyrightText = "Deutsche Telekom AG"
SPDX-License-Identifier = "BSD-3-Clause"


[[annotations]]
path = [
    ".gitignore",
    "README.md",
    "REUSE.toml",
    "docs/**",
    ".github/**"
]
SPDX-FileCopyrightText = "Deutsche Telekom AG"
SPDX-License-Identifier = "CC0-1.0"


[[annotations]]
path = [
    "gen/yang/CiscoIosXr_24_1_ncs55a1/*.yang",
]
SPDX-FileCopyrightText = "2019-2023 by Cisco Systems, Inc. All rights reserved."


# See https://github.com/Juniper/yang/blob/master/LICENSE
[[annotations]]
path = [
    "gen/yang/JuniperCRPD_23_4R1_9/*.yang",
]
SPDX-FileCopyrightText = "2025 Juniper Networks, Inc. All rights reserved."
SPDX-License-Identifier = "Apache-2.0"


# See https://github.com/nokia/srlinux-yang-models/blob/v25.3/LICENSE
[[annotations]]
path = [
    "gen/yang/NokiaSRLinux_25_3_2/*.yang",
]
SPDX-FileCopyrightText = "2021, Nokia. All rights reserved."
SPDX-License-Identifier = "BSD-3-Clause"
