TESTENV=sorespo-quicklab-crpd

ROUTERS_CRPD=sto-core-1 lju-core-1 ams-core-1 fra-core-1
ROUTERS_FRR=cust-1 cust-2 cust-3 cust-4

include ../common/clab.mk
include ../common/containers.mk
include ../common/quicklab.mk

start: licenses/juniper_crpd24.lic
