TESTENV=respnet-quicklab-crpd

ROUTERS_XR=
ROUTERS_CRPD=sto-core-1 lju-core-1 ams-core-1 fra-core-1 cust-1 cust-2 cust-3 cust-4

include ../common/clab.mk
include ../common/containers.mk
include ../common/quicklab.mk
