name: Test

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - id: setup-acton
        uses: actonlang/setup-acton@v1
        with:
          channel: 'tip'
      - name: "Check out repository code"
        uses: actions/checkout@v4
      - name: "Cache acton stuff"
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/acton
            out
          key: acton-${{ hashFiles('**/build.act.json') }}-${{ steps.setup-acton.outputs.version }}
      - name: "Ensure generated code is up to date"
        run: |
          make gen
          git diff --exit-code
      - run: acton build
      - run: acton test
      - run: acton test perf
      - uses: actions/upload-artifact@v4
        with:
          name: sorespo-linux-x86_64
          path: out/bin/sorespo
      - run: acton build --target aarch64-linux-gnu.2.27
      - uses: actions/upload-artifact@v4
        with:
          name: sorespo-linux-aarch64
          path: out/bin/sorespo
      - run: acton build --target aarch64-macos
      - uses: actions/upload-artifact@v4
        with:
          name: sorespo-macos-aarch64
          path: out/bin/sorespo

  release:
    # Only run on the main branch
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      # Required for uploading release assets
      contents: write
    needs: build-and-test
    env:
      TAG: tip
    steps:
      - name: "Check out repository code"
        uses: actions/checkout@v4
      - name: Delete tag
        run: gh release delete ${{ env.TAG }} --cleanup-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Download all binary artifacts"
        uses: actions/download-artifact@v4
        with:
          pattern: sorespo-*
      - name: "Compress binary artifacts"
        run: |
          tar -czf sorespo-linux-x86_64.tar.gz -C sorespo-linux-x86_64 sorespo
          tar -czf sorespo-linux-aarch64.tar.gz -C sorespo-linux-aarch64 sorespo
          tar -czf sorespo-macos-aarch64.tar.gz -C sorespo-macos-aarch64 sorespo
      - name: "Upload artifacts as release packages"
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "sorespo-*.tar.gz"
          draft: false
          prerelease: true
          name: ${{ env.TAG }}
          tag: ${{ env.TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          replacesArtifacts: true

  net-test:
    strategy:
      fail-fast: false
      matrix:
        TESTENV: [quicklab, quicklab-crpd, quicklab-notconf, quicklab-srl]
        ARCH: [linux-x86_64, linux-aarch64]
        exclude:
          # No Cisco IOS XRd support for aarch64 :/
          - TESTENV: quicklab
            ARCH: linux-aarch64
    runs-on: ${{ matrix.arch == 'linux-x86_64' && 'ubuntu-24.04' || 'ubuntu-24.04-arm' }}
    env:
      IMAGE_PATH: ${{ secrets.IMAGE_PATH || format('ghcr.io/{0}/', github.repository) }}
    needs: build-and-test
    steps:
      - name: Set up env for containers
        run: |
          # IOS XRd
          sudo sysctl -w fs.inotify.max_user_instances=64000
          # cRPD
          sudo apt-get update
          sudo apt-get install -qy linux-modules-extra-$(uname -r)
          sudo modprobe mpls_router mpls_gso vrf
      - name: "Check out repository code"
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: sorespo-${{ matrix.ARCH }}
          path: out/bin/
      - run: chmod a+x out/bin/sorespo
      - name: "Check out licenses repo"
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/licenses
          path: licenses
          ssh-key: ${{ secrets.LICENSES_PRIVATE_KEY }}
      # If we're using IMAGE_PATH=ghcr.io/... login to ghcr.io using GITHUB_TOKEN
      # TODO: what about other (external) registries that require login?
      - name: Login to ghcr.io
        if: ${{ startsWith(env.IMAGE_PATH, 'ghcr.io') }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: "Start quicklab"
        run: |
          if [ "${{ matrix.TESTENV }}" = "quicklab" ]; then
            make -C test/${{ matrix.TESTENV }} start wait WAIT=240
            echo "Sleeping for 60s to give IOS XRd more time to get ready ..."
            sleep 60
          elif [ "${{ matrix.TESTENV }}" = "quicklab-srl" ]; then
            make -C test/${{ matrix.TESTENV }} start wait
            echo "Sleeping for 30s to give SR Linux more time to get ready ..."
            sleep 30
          else
            make -C test/${{ matrix.TESTENV }} start wait
          fi
      - name: "Configure quicklab"
        run: |
          make -C test/${{ matrix.TESTENV }} copy run-and-configure
      - name: "Run quicklab tests"
        run: |
          timeout 120 bash -c 'until make -C test/${{ matrix.TESTENV }} test; do echo "Retrying..."; sleep 2; done'
      - run: |
          make -C test/${{ matrix.TESTENV }} save-logs
        if: ${{ always() }}
      - uses : actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.TESTENV }}-${{ matrix.ARCH }}
          path: test/${{ matrix.TESTENV }}/logs
        if: ${{ always() }}
